import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const dm_sans = DM_Sans({ subsets: ['latin'], variable: '--font-dm_sans', weight: ['400', '700'] });

export const metadata: Metadata = {
  title: 'Photosnap Multi Page Website',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={dm_sans.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
